# config.toml
# Config generation tool: https://j-hc.github.io/rvmm-config-gen/

[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change header'"
excluded-patches = "'Disable precise seeking gesture' 'Seekbar tapping' 'Always repeat' 'Tablet mini player' 'Hide timestamp' 'Hide info cards' 'Hide seekbar' 'Wide searchbar' 'Hide captions button' 'Hide player buttons' 'Alternative thumbnails' 'Spoof app version'"

[Instagram]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Music]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Twitch]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Messenger]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Twitter]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"


