[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"

[Instagram]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Messenger]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Twitter]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Custom branding' 'Disable suggested video end screen'"
excluded-patches = "'Tablet mini player' 'Hide captions button' 'Spoof app version' 'Enable tablet layout' 'Custom player overlay opacity' 'Hide info cards' 'Hide filter bar' 'Hide 'Load more' button' 'Disable rolling number animations' 'Hide timestamp' 'Wide searchbar' 'Always autorepeat' 'Spoof device dimensions'"

[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

